"""Add game_user Association Table

Revision ID: 4ca7dd355f49
Revises: 38e2085bf9db
Create Date: 2024-03-21 16:47:49.233433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca7dd355f49'
down_revision = '38e2085bf9db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
